### ISSUE TITLE
apache::htpasswd does not support the same username in multiple htpasswd files

### ISSUE THREAD

**Issue by ghost** [example42/puppet-apache#54]
apache::htpasswd uses the name of the resource as the username to be added to the htpasswd file, and does not provide a way to override that username.  That causes a problem when you want to have the same username defined in two different htpasswd files on the same node.  If I try to create entries for user1 in both /etc/htpasswd1 and /etc/htpasswd2, I'll get a resource conflict.

A simple solution to this would be to add an additional parameter to apache::htpasswd called ```username``` that defaults to $name.

**Comment by tiengo** [comment]
Solved in PR #75
