### ISSUE TITLE
clean vhost dir before creating new

### ISSUE THREAD

**Issue by joao-matos** [example42/puppet-apache#80]
Hi

If the there is  a need to replace an existing vhost conf file with another one, the old remains and the new is created.

It could delete existing files and create new files.

Regards

**Comment by alvagante** [comment]
If the vhost name is the same of an existing .conf file, that should be replaced.
Can you provide a  sample code / context when this is not done?

**Comment by joao-matos** [comment]
lets say you have a vhost called aaa and other called bbb . if you want bbb to become the first you change their names so bbb still bbb but aaa becomes ccc. While deploying this, ccc will be deployed and aaa will remain there. I know i can just swap the configuration from one vhost to the other. but if you use a vhost naming based on the domain, for example, you end up with multiple files and having to use ensure absent to remove old links.

**Comment by alvagante** [comment]
Then just keep the aa vhost and set enable to false, to remove it.

**Comment by joao-matos** [comment]
it ain't the cleanest solution but it's an option. thanks

**Comment by alvagante** [comment]
An alternative is to force the purging of all the files not managed by Puppet in the virtual hosts dir, you can do that in your local modules.
