### ISSUE TITLE
Module in forge.puppet.com has wrong dependency issue

### ISSUE THREAD

**Issue by lansz** [example42/puppet-apache#91]
I got this error when use this module from forge.puppetlabs.com

```
Unable to find module 'example42-concat' on https://forgeapi.puppetlabs.com
```
A none exists module is listed in https://forge.puppetlabs.com/example42/apache/dependencies.

**Comment by alvagante** [comment]
Pushed version 2.1.11 with updated dependency, thanks for reporting
